apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: authorizationservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: authorizationservice
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: authorizationservice
        image: raniotitonk/authorizationservice
        ports:
        - containerPort: 80
        - containerPort: 443
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Test"
        volumeMounts:
        - name: cert
          mountPath: "/https"
          readOnly: true
        livenessProbe:
          httpGet:
            path: /health/live
            port: 80
          periodSeconds: 60
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 80
          periodSeconds: 60
      volumes:
      - name: cert
        secret:
          secretName: authorizationservice-cert
---
apiVersion: v1
kind: Service
metadata:
  name: authorizationservice
spec:
  selector:
    app: authorizationservice
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
    - protocol: TCP
      name: https
      port: 443
      targetPort: 443

  type: ClusterIP